### ISSUE TITLE
How to get CSS in SVG

### ISSUE THREAD

**Issue by mzfr** [niklasf/python-chess#299]
[Here](https://python-chess.readthedocs.io/en/latest/svg.html#chess.svg.board) it says that we can add css to the svg image we generate. But how can I do it. I mean will it need only CSS ? or also some HTML ?
For example I have this:
```Css
table tr td {
  width: 20px;
  height: 20px;
  border: solid #000 1px;
}

table tr:nth-child(odd) td:nth-child(even) {
  background: #000;
}
table tr:nth-child(even) td:nth-child(odd) {
  background: #000;
}
```
And with HTML
```html
<table>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
        <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
        <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
        <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
        <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
        <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
        <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
        <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
```
This gives me a chess board. so will I have to do something like this ? also will I have to pass a path of the file or all the css must be there as a string

**Comment by niklasf** [comment]
Here's a sample stylesheet that just changes some colors:

```css
.square.light {
  fill: #dee3e6;
}
.square.dark {
  fill: #8ca2ad;
}

.square.light.lastmove {
  fill: #c3d889;
}
.square.dark.lastmove {
  fill: #92b167;
}

.check {
  fill: url(#check_gradient);
}
```

You can pass it to the `chess.svg.board(style=...)` argument. Hope this helps.
