### ISSUE TITLE
CSS stylesheet example (to alter SVG board elements)

### ISSUE THREAD

**Issue by PedanticHacker** [niklasf/python-chess#622]
There's no CSS stylesheet example in the repo. It would be nice to have an example which can then be copy-pasted and altered to one's desire and needs.

**Comment by PedanticHacker** [comment]
```
default_stylesheet = """
.square.light {
    stroke: yellow;
    fill: yellow;
}

.square.dark {
    stroke: black;
    fill: black;
}

.circle {
    stroke: red;
    fill: red;
}

.arrow {
    stroke: blue;
    fill: blue;
}
"""
```
`Is my CSS stylesheet even correct? It does not work. I pass this variable to chess.svg.board(..., style=default_stylesheet). Damn docs not having any example!`

**Comment by PedanticHacker** [comment]
![image](https://user-images.githubusercontent.com/14254085/91886347-8092cb00-ec89-11ea-860b-62fbf2db7a01.png)
Notice how the black queen is colored and nothing else changed.

The stylesheet passed to the `style` argument of `chess.svg.board()` was this:
```
my_custom_stylesheet = """
square.light {
    stroke: yellow;
    fill: yellow;
}

square.dark {
    stroke: black;
    fill: black;
}

circle {
    stroke: red;
    fill: red;
}

arrow {
    stroke: blue;
    fill: blue;
}
"""
```
This is getting very frustrating. **PLEASE** help me out!

**Comment by niklasf** [comment]
The stylesheet looks sensible, but not all SVG renderers support CSS. I'll think about a more reliable way to use custom colors.

**Comment by niklasf** [comment]
Actually your SVG renderer seems to support CSS, as hinted at by the red crown of the black queen. But there are some subtle mistakes in the stylesheet. The following might be worth a try:

```css
.square.light {
    stroke: yellow;
    fill: yellow;
}

.square.dark {
    stroke: black;
    fill: black;
}

.circle {
    stroke: red;
    fill: red;
}

.arrow {
    stroke: blue;
    fill: blue;
}
```
